### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by mbj**
The current schema causes the conditional always to evaluate to true, so it can be dropped.

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb Ready for review.

This was causing some extra queries that where disturbing me on debugging.

**Comment by dkubb** [comment]
@mbj it looks like this change broke the build. I re-ran the tests once and they still fail.

**Comment by mbj** [comment]
> @mbj it looks like this change broke the build. I re-ran the tests once and they still fail.

It looks like the `rake test_app` is broken with that change. This will be implicitly resolved with the change in #127 that does remove the "temporal" dependency in ENV loading and the db schema state.

**Comment by mbj** [comment]
Closing this for now, will be done after #127.

**Pull request closed without merging**
