### PR TITLE
Remove dangerous admin UI

### PR DESCRIPTION
**Pull request by mbj**
The admin UI does not provide a way to group a set edits togeher to
happen in a single system transaction.

Updates on the object graph so are by nature partial. Administrative
actions that require more than object to be changed to bring the
system into the desired state are imposible.

In larger (volume) installations a single partial edit to
Countries / Zones / States can easily cause a high number of errors,
or worse violated busines rules.

For these installations the changes are typically carried out using
operational migrations within a single system transaction.

Many UI endpoints (and also API endpoints, through they are not covered
by this change right now) are under that consideration effectively dead.
As cannot be used without the high chance of reduction operational
value.

Carrying these endpoints around makes no sense hence we kill them. And with
them all the bugs they can trigger such as FK violations.

This commit kills the admin endpoints for Countries, State and Zones.
Also as these yielded a high number of schema violations and thus
caused unneded friction.

Extracted from #127 that had to deal with lots of violated FKs in the deleted code. Especially from specs.

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb Ready for review.

**Comment by dkubb** [comment]
@mbj OT: but are there api controllers that can be removed too? Some of the api end-points only exist to support parts of the admin UI.

**Comment by mbj** [comment]
> @mbj OT: but are there api controllers that can be removed too? Some of the api end-points only exist to support parts of the admin UI.

I thought about that one and the initial change did that. But than I realized the checkout for example needs the states API controller, and before I go to deep and break something unintended. Also the API is already green with #127 and to streamline I think we should not currently expand the change there.

**Comment by dkubb** [comment]
@mbj code-wise I am fine with this. Going to do a quick run through the admin UI to make sure some of the other config areas still work fine.

**Pull request merged**
