### PR TITLE
Change locking to be controlled by postgres connection state

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb This is ready for review. This change is paired with a per connection `SET lock_timeout TO $value` in our application instance.

**Comment by dkubb** [comment]
> This change is paired with a per connection SET lock_timeout TO $value in our application instance.

How are you actually setting this?

**Comment by mbj** [comment]
> How are you actually setting this?

On each connection object before it gets put into the pool, via another AR monkey patch that adds the call to this method: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L704

**Comment by dkubb** [comment]
@mbj I would suggest adding the monkey patch first and then enabling it with this PR.

**Comment by mbj** [comment]
@dkubb I only wanted to get a code review here, to parallelize the review with my other activities. The monkey patch goes to our private app.

**Pull request merged**
