### PR TITLE
Remove support for applying coupon codes

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb This is ready for review.

**Comment by dkubb** [comment]
@mbj does it matter that the term "coupon" appears in quite a few other files:

```
$ ag -il coupon
api/app/controllers/spree/api/checkouts_controller.rb
api/app/controllers/spree/api/promotions_controller.rb
api/app/views/spree/api/orders/could_not_apply_coupon.v1.rabl
api/spec/controllers/spree/api/checkouts_controller_spec.rb
backend/app/assets/stylesheets/spree/backend/sections/_orders.scss
backend/spec/features/admin/promotion_adjustments_spec.rb
core/app/models/spree/calculator/price_sack.rb
core/app/models/spree/order.rb
core/app/models/spree/promotion.rb
core/app/models/spree/promotion_handler/coupon.rb
core/config/rubocop.yml
core/config/locales/en.yml
core/lib/spree/permitted_attributes.rb
core/spec/models/spree/promotion/rules/first_order_spec.rb
core/spec/models/spree/promotion/rules/one_use_per_user_spec.rb
core/spec/models/spree/promotion/rules/item_total_spec.rb
core/spec/models/spree/promotion/rules/product_spec.rb
core/spec/models/spree/promotion/rules/user_logged_in_spec.rb
core/spec/models/spree/promotion_handler/coupon_spec.rb
core/spec/models/spree/promotion_spec.rb
```

**Comment by dkubb** [comment]
@mbj assuming my last question doesn't matter, I am fine with this change and will merge once I hear back.

**Comment by mbj** [comment]
> @mbj does it matter that the term "coupon" appears in quite a few other files:

This PR is only about the code path that "apply a user (or admin provided) coupon code" to an order. Not the processing of coupon promotions. I plan to kill that also but wanted to do a small iteration.

**Comment by dkubb** [comment]
> This PR is only about the code path that "apply a user (or admin provided) coupon code" to an order. Not the processing of coupon promotions. I plan to kill that also but wanted to do a small iteration.

Ok, then I will merge this once the build is green.

**Pull request merged**
