### PR TITLE
Remove excess whitespace

### PR DESCRIPTION
**Pull request by dkubb**
This branch makes two changes:

* Remove trailing whitespace
* Replace leading tabs with 2 spaces

### CODE REVIEW

**Comment by dkubb** [comment]
@mbj this is ready for review.

**Comment by dkubb** [comment]
@mbj nevermind. Looks like I have some alive mutants to fix ;)

This is an interesting use case though. Should mutant's `--since` flag filter out whitespace-only changes? I think we'd only really want mutant to execute for changes to the AST.

**Comment by mbj** [comment]
Lets discuss the style changes under mutation testing in channel. Yes mutant should ignore whitespaces.

**Comment by dkubb** [comment]
@mbj assuming all green, this should be ready for review.

**Comment by mbj** [comment]
@dkubb See https://github.com/MountainRoseHerbs/spree/commit/439d75bb4ed82d2618494d6347772a509ec4c70a#comments

**Comment by mbj** [comment]
@dkubb I'm fine with the diff and ready to merge when the last build is green.

**Comment by dkubb** [comment]
@mbj ok the build is green now.

**Pull request merged**
