### PR TITLE
Cleanup dotfiles

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb Ready for review after #95

**Comment by dkubb** [comment]
@mbj should these commits be squashed?

**Comment by mbj** [comment]
> @mbj should these commits be squashed?

I'm fine with either one. Do we miss a rule here?

**Comment by dkubb** [comment]
> I'm fine with either one. Do we miss a rule here?

I don't know if we've ever formalized a rule for this one. We have talked about making commits be as small as possible before. I don't know if we have any exceptions to this rule.

I think maybe the reason I flagged this is because it's a removal. When removing from a repo, we *could* remove each file one at a time, but we typically remove as much as possible per commit as in your guide removal.

With additions and changes you typically want as small possible commits because you have lots of stuff to wade through as a reviewer. And if something goes wrong, you want as small as scope as possible to step through until you find the offending code.

With a removal, I'm not sure if there's the same concerns, it might be simpler to batch up removal in as few commits as possible. I'm open for discussion on this since I'm just going by intuition here and have not thought deeply about this yet.

**Comment by mbj** [comment]
> I don't know if we've ever formalized a rule for this one. We have talked about making commits be as small as possible before. I don't know if we have any exceptions to this rule.

I think that each commit should come with its own justification. We are removing files that are considered important by many (example `.travis.yml`) so we should have an explanation in the commits message.

The files are not related to each other, so each one needs a separate justification, AKA separate commit.

**Comment by dkubb** [comment]
> The files are not related to each other, so each one needs a separate justification, AKA separate commit.

This is a good point. If they were related then you could apply my argument, maybe, but since they are distinct and unrelated I agree we should keep them separated.

**Pull request merged**
