### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb This is ready for review.

**Comment by dkubb** [comment]
@mbj it looks like various parts of the build are failing.

**Comment by mbj** [comment]
> @mbj it looks like various parts of the build are failing.

This is from a devtools update. I consider to nail devtools to the old version to overcome this for now.

**Comment by dkubb** [comment]
> I consider to nail devtools to the old version to overcome this for now.

@mbj this is fine with me as long as it's a temporary measure.

**Comment by mbj** [comment]
@dkubb This is ready for the next pass.

**Pull request merged**
