### PR TITLE
Reduce checkout mixin

### PR DESCRIPTION
**Pull request by mbj**
Depends on #478

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb This is ready for review.

**Comment by dkubb** [comment]
@mbj can you amend the commit to explain why it's ok to remove this code? I'm not entirely clear why or how it can be removed just by looking.

**Comment by mbj** [comment]
> @mbj can you amend the commit to explain why it's ok to remove this code? I'm not entirely clear why or how it can be removed just by looking.

Sorry, this is an extraction of a more complex change and I missed to do so. In summary: It has no call sides that depend on the semantic effect.

**Comment by mbj** [comment]
I'll do an explicit validation against or main app before we should continue with that one. And amend the commit with the information.

**Comment by mbj** [comment]
@dkubb This is ready for review as explicitly validated against our main app.

**Comment by dkubb** [comment]
@mbj I am fine with this change. I will merge on green.

**Pull request merged**
