### PR TITLE
Add incremental mutant test to build process

### PR DESCRIPTION
**Pull request by dkubb**

### CODE REVIEW

**Comment by dkubb** [comment]
@mbj this is ready for review.

**Comment by mbj** [comment]
@jdutil, I want to get this one upstreamed asap. As it helps to prevent accident low quality changes via enforcing all touched code has full mutation coverage. It does NOT require *all* code that is present (but not touched) to qualify for mutation coverage. Will you accept such a change?

**Comment by JDutil** [comment]
Yeah

**Comment by dkubb** [comment]
@mbj should we add `--fail-fast` to the mutant command line arguments to enable faster feedback?

**Comment by JDutil** [comment]
I've received complaints in the past about --fail-fast so don't care what you guys do but probably best to not upstream that so theres full feedback.

**Comment by mbj** [comment]
@JDutil `--fail-fast` for mutant works different than rspec ones. I agree on `--fail-fast` for rspec does not make too much sense.

**Pull request merged**
