### PR TITLE
Refactor specs to be stricter

### PR DESCRIPTION
**Pull request by dkubb**
This branch refactors the specs to use stricter semantics so that if behaviour should break due to a stronger validation being added the specs will fail rather than hiding the failure.

### CODE REVIEW

**Comment by dkubb** [comment]
@mbj I wanted to get your input on this. I would like to keep the stricter specs and the linting, but I'm not sure about the stricter methods I used in the 3rd commit.

I mean, I certainly don't trust spree's specs to cover all the code, but I also don't like the idea of those methods being used and the return values not being checked. I'd rather put it through a bunch of local and staging testing, and then test it live to see if it exposes any issues we never knew about.

**Comment by mbj** [comment]
@dkubb I think the 4th commit actually is absolutely require., we should keep it. When upstreaming this commit successfully, there will be much more healthy backpressure form the spec setup, resulting in less bugs hitting us downstream. Applying the 4th commit against master should be done carefully to include any other method call that has been added in weak form meanwhile.

**Comment by mbj** [comment]
@dkubb I just realized you wanted to have feedback and you did not ask for a review / merge yet. In case this was not your intention, lets pop the commits from this branch.

**Comment by dkubb** [comment]
@mbj I am fine with merging this if you are ok with it. I would prefer we start with stricter requirements up-front, and fix things as needed, than to proceed without having full confidence that the code is doing what is intended.

**Pull request merged**
