### PR TITLE
Remove stock movements and transfers

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb Ready for review.

**Comment by dkubb** [comment]
@mbj I think I may have found a couple more references to stock movements:

```
12:03:49 spree (fix/remove-spree-stock-movements) $ ag movement
api/config/locales/en.yml
26:      stock_location_required: "A stock_location_id parameter must be provided in order to retrieve stock movements."

core/spec/models/spree/inventory_unit_spec.rb
130:    it "should create a stock movement" do
```

**Comment by mbj** [comment]
@dkubb I fixed the occurrences you found, but not via removal but rewording as they still are valid but in a different case (without stock movements). Next passes will also take out these cases, but I figured to start at the leaves.

**Comment by mbj** [comment]
@dkubb Ready for the next pass.

**Comment by dkubb** [comment]
@mbj I am fine with these changes. It will require more integration testing with mrh-spree, but I am fine to merge this when green.

**Pull request merged**
