### PR TITLE
Remove backend payment edits

### PR DESCRIPTION
**Pull request by mbj**

### CODE REVIEW

**Comment by dkubb** [comment]
@mbj do we replace this functionality on the mrh-spree side? I know that occasionally CSRs do edit the payment amounts to match the order totals.

**Comment by mbj** [comment]
> @mbj do we replace this functionality on the mrh-spree side? I know that occasionally CSRs do edit the payment amounts to match the order totals.

Even better on the main app side I automated the payment amount updates on order content changes in the admin.

**Comment by dkubb** [comment]
> I automated the payment amount updates on order content changes in the admin.

Oh that is way better. I assume it won't *increase* the payment amount, but will automatically decrease it when it can? Once a payment is authorized you can't increase it, but you are allowed to decrease it.

**Comment by mbj** [comment]
> Oh that is way better. I assume it won't increase the payment amount, but will automatically decrease it when it can? Once a payment is authorized you can't increase it, but you are allowed to decrease it.

There is verbose discussion in the main app. Lets discuss there.

**Pull request merged**
