### PR TITLE
Remove redundant specs

### PR DESCRIPTION
**Pull request by mbj**
Extraction from #398

### CODE REVIEW

**Comment by mbj** [comment]
@dkubb This is ready for review.

**Comment by dkubb** [comment]
@mbj was this verified by running mutant against `Spree::Order#finalize!` to make sure the remaining specs killed all the mutants in that method?

**Comment by mbj** [comment]
> @mbj was this verified by running mutant against Spree::Order#finalize! to make sure the remaining specs killed all the mutants in that method?

I was fooled by `--since` active on CI, sorry for that. We need inverse tracking to make `--since` more relevant. Testing manually now.

**Comment by mbj** [comment]
@dkubb All mutations are dead on:

```
RAILS_ENV=test bundle exec mutant -j 1 --use rspec --require ./spec/dummy/config/environment -- 'Spree::Order#complete_order' 'Spree::Order#finalize!'
```

We still need `-j1` as the global zone from specs still leaks.

**Pull request merged**
